name: Build and Zip Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Copy Chrome manifest and zip
      run: |
        cp manifest-chrome.json manifest.json
      shell: bash

    - name: Upload Chrome artifact
      uses: actions/upload-artifact@v2
      with:
        name: element-shuffler-chrome
        path: .

    - name: Copy Firefox manifest and zip
      run: |
        cp manifest-firefox.json manifest.json
      shell: bash

    - name: Upload Firefox artifact
      uses: actions/upload-artifact@v2
      with:
        name: element-shuffler-firefox
        path: .